# ─────────────────────────────────────────────────────────────────────────────
# ServiceAccount — bound to GCP SA via Workload Identity
# ─────────────────────────────────────────────────────────────────────────────
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "payment-orchestrator.serviceAccountName" . }}
  namespace: {{ include "payment-orchestrator.namespace" . }}
  labels:
    {{- include "payment-orchestrator.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.gcp.projectId }}
    iam.gke.io/gcp-service-account: payment-orchestrator-app@{{ .Values.gcp.projectId }}.iam.gserviceaccount.com
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
